### ISSUE TITLE
KDE 6 support

### ISSUE THREAD

**Issue by CountMurphy** [MathisP75/daemon-dotfiles#3]
I adore this theme. Every time I boot up, it makes me happy. I just learned that a major KDE upgrade is on the horizon: https://kde.org/announcements/megarelease/6/.  Do we know if this theme will be compatible?

**Comment by MathisP75** [comment]
I think it should be compatible, but I had planned a refreshed version of it for Plasma 6 anyways.

**Comment by CountMurphy** [comment]
That's great to hear! Thank you for your work on this.

**Comment by MathisP75** [comment]
Since you expressed so much interest in this project, I wanted to let you know that I have started work on a refreshed version. This one will be more consistent, more thoughtfully made and even more cyberpunk!

Here's the new repository: https://github.com/MathisP75/daemon-kde-mk2

A work in progress of the kvantum theme:
![Screenshot_20240326_193055.png](https://github.com/MathisP75/daemon-dotfiles/assets/98901170/e6db063a-07d7-4e71-9708-8782ba35600d)

**Comment by CountMurphy** [comment]
Holy crap, that looks amazing. I'll check that out today. Thanks for the heads up!
